// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0SyYVyI8vIg6QCzYfxe9iSbUmzoA5TM',
    appId: '1:824878884531:web:7757b293bb3815308272c6',
    messagingSenderId: '824878884531',
    projectId: 'presence-31499',
    authDomain: 'presence-31499.firebaseapp.com',
    storageBucket: 'presence-31499.appspot.com',
    measurementId: 'G-6MVPDXEMK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zPMdMu0n3WXUzCMsXDvOhH0qDwUQeEE',
    appId: '1:824878884531:android:a149760cc10e40338272c6',
    messagingSenderId: '824878884531',
    projectId: 'presence-31499',
    storageBucket: 'presence-31499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnaBN25k82Z9hBDpxTX6BAfz2eQqRyq0',
    appId: '1:824878884531:ios:d9b9c62bd2e7321e8272c6',
    messagingSenderId: '824878884531',
    projectId: 'presence-31499',
    storageBucket: 'presence-31499.appspot.com',
    iosClientId: '824878884531-kkt3tg3mn8jm1qm54e3h2romduuhcj0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApp',
  );
}
